### ISSUE TITLE
Concurrent transactions causing duplicated sequence number

### ISSUE THREAD

**Issue by tiagoraposeiraff** [vaened/laravel-sequenceable#4]
I was testing your package and using tinker on 4 different terminals with a loop to create multiple models that use the sequenceable trait, I detected duplicated sequencer number.

In my case, I have a client scope, so the model should set the order based on a client id column. For that same client id there were sequence numbers that showed up 2 or even 3 times (for 1.5k records I had about 8 or 9 duplicated sequence numbers).

Have you consider using a `SELECT FOR UPDATE` statement? Locking the sequence should prevent race conditions like the one I'm having.

**Comment by vaened** [comment]
You are absolutely right. Initially, I designed this library for a mid-sized project, and until now, I had not encountered concurrency issues. However, I have reviewed and updated the relevant methods (**incrementByOne** and **setValue**) to include proper handling of locks and transactions. These improvements should ensure the integrity of sequence data under high concurrency conditions.

I apologize for the delay in my response. I appreciate your contribution in identifying this issue.

Thank you again for your help in improving the library.
